# vi:set filetype=dockerfile :

# NEVER PUBLISH THE DOCKER IMAGE
# ssh private keys are saved
FROM ubuntu:xenial

<%
  require "yaml"
  config = YAML.load_file("./config.yml")
-%>

ENV SERVE_HTTP_ADDRESS <%= config["http"]["address"] %>
ENV SERVE_HTTP_PORT <%= config["http"]["port"] %>
ENV BASIC_USERNAME <%= config["auth"]["user"] %>
ENV BASIC_PASSWORD <%= config["auth"]["password"] %>
ENV BUILD_URL http://$BASIC_USERNAME:$BASIC_PASSWORD@$SERVE_HTTP_ADDRESS:$SERVE_HTTP_PORT
ENV USER dev
ENV HOME /home/$USER
ENV LANG en_US.utf8

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y vim sudo software-properties-common python-software-properties apt-utils \
      wget curl \
      manpages manpages-dev freebsd-manpages funny-manpages man2html manpages-posix manpages-posix-dev \
      locales tzdata \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 \
    && echo "$USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && useradd -m $USER && echo "$USER:$USER" | chpasswd \
    && adduser $USER sudo \
    && echo "Europe/Berlin" > /etc/timezone \
    && echo "set term=ansi" >> $HOME/.vimrc \
    && ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && apt-get autoremove -y

# SSH config
RUN apt-get update -y\
    && apt-get install -y openssh-client \
    && mkdir $HOME/.ssh \
    <% for key in config["ssh"]["keys"] -%>
    && curl $BUILD_URL/.ssh/<%= key %> -o $HOME/.ssh/<%= key %> \
    && chmod 400 $HOME/.ssh/<%= key %> \
    && chown $USER $HOME/.ssh/<%= key %> \
    <% end -%>
    && apt-get autoremove -y
COPY ssh_config /etc/ssh/ssh_config

# GIT config
RUN apt-get update \
    <% for key in config["git"]["files"] -%>
    && curl $BUILD_URL/<%= key %> -o $HOME/<%= key %> \
    && chmod a+rwx $HOME/<%= key %> \
    <% end -%>
    && apt-get -y install git git-flow \
    && chown $USER: $HOME/.ssh/<%= config['ssh']['keys'].first %>\
    && eval $(ssh-agent -s) \
    && ssh-add $HOME/.ssh/<%= config['ssh']['keys'].first %>\
    && git clone git@github.com:avarteqgmbh/git_flow_hooks.git $HOME/git_flow_hooks \
    && git config --global gitflow.path.hooks $HOME/git_flow_hooks/hooks \
    && git config --global gitflow.prefix.versiontag v \
    && apt-get autoremove -y

# ZSH config
RUN apt-get update \
    && ln -s /store/zsh/zsh_history $HOME/.zsh_history \
    && apt-get -y install zsh \
    && git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh \
    && chsh -s /bin/zsh $USER \
    && apt-get autoremove -y

# general tools and dependencies
RUN apt-get update -y \
    && apt-get install -y \
        mysql-client postgresql-client mongodb-clients redis-tools \
        jq net-tools netcat telnet dnsutils inetutils-traceroute \
        apt-transport-https \
        bzip2 g++ gcc make libc6-dev zlib1g-dev libyaml-dev libsqlite3-dev sqlite3 \
        autoconf libgmp-dev libgdbm-dev libncurses5-dev automake libtool bison pkg-config \
        libffi-dev libgmp-dev libreadline6-dev libssl-dev libpq-dev \
        libmysqlclient-dev \
        libxslt-dev libxml2-dev\
        libmagickwand-dev imagemagick \
        python-pip python-dev build-essential \
    && apt-get autoremove -y

RUN pip install --upgrade pip \
    && pip install --upgrade virtualenv

<% for m in config["modules"] -%>
COPY modules/<%= m %>.sh /tmp
RUN su -c /tmp/<%= m %>.sh - $USER \
    && rm /tmp/<%= m %>.sh
<% end -%>

# Configs that might change often should be added last
COPY zshrc $HOME/.zshrc.tmp
RUN mv $HOME/.zshrc $HOME/.zshrc.orig \
    && cat $HOME/.zshrc.tmp $HOME/.zshrc.orig > $HOME/.zshrc \
    && rm $HOME/.zshrc.tmp $HOME/.zshrc.orig
COPY inputrc $HOME/.inputrc
COPY rvmrc $HOME/.rvmrc
RUN chown $USER: $HOME/.zshrc $HOME/.inputrc

WORKDIR /work
USER $USER

CMD /bin/zsh
